function Get-TerraformProviderDocHarvest {
    # Not exported. Lists one provider version's docs and fetches every page's markdown from
    # the public registry. Probed 2026-10-06:
    #
    #   Version id: GET https://registry.terraform.io/v2/providers/<namespace>/<name>?include=provider-versions
    #     included[] holds every version (see Get-TerraformRegistryHarvest). hashicorp/null
    #     3.2.3 is { "type": "provider-versions", "id": "59862", "attributes": { "version": "3.2.3", ... } }.
    #
    #   Listing: GET https://registry.terraform.io/v2/provider-versions/<id>?include=provider-docs
    #     The listing endpoint in the task, /v2/provider-versions/<id>/provider-docs, is 404.
    #     The include returns every doc in one response (1645 for azurerm 5.8.0, no paging).
    #     /v2/provider-docs?filter[provider-version]=<id> also lists, but ignores page[size]
    #     and pages by 1, so it is not used. One included[] element (null 3.2.3):
    #       { "type": "provider-docs", "id": "6794557",
    #         "attributes": { "category": "resources", "language": "hcl",
    #           "path": "docs/resources/resource.md", "slug": "resource", "subcategory": null,
    #           "title": "resource", "truncated": false },
    #         "links": { "self": "/v2/provider-docs/6794557" } }
    #     Categories seen: overview, guides, resources, data-sources, plus functions,
    #     ephemeral-resources, list-resources and actions (azurerm 5.8.0, local 2.9.1). Only
    #     the first four are kept. Languages other than hcl (cdktf) are skipped. The slug is
    #     usually the type without the provider prefix (resource_pool for
    #     vsphere_resource_pool) but some providers keep it (vsphere_sso_group).
    #
    #   Content: GET https://registry.terraform.io/v2/provider-docs/<doc id>
    #     data.attributes has category, content (raw markdown, front matter included),
    #     language, path, slug, subcategory, title, truncated. null 3.2.3 resource starts:
    #       ---\n# generated by https://github.com/hashicorp/terraform-plugin-docs\n
    #       page_title: "null_resource Resource - terraform-provider-null"\nsubcategory: ""\n...
    #
    # Returns one record per kept doc: Category, Title, Subcategory, Slug, Content.
    # Content requests go through Invoke-TerraformRegistryRequestSet (the shared rate state);
    # if any page still fails, it throws and nothing is returned.
    #
    # Checkpoint: with -PartialPath, the pages fetched so far are written there every
    # $script:TerraformDocCheckpointPages pages, and once more on the way out whenever this
    # run fetched any (a failed page, an exception, Ctrl+C: the finally block runs on pipeline
    # stop; and on success too, so a stop between here and the cache write loses nothing).
    # With -Resume, a partial file for the same registry version id supplies its pages and
    # only the rest are requested; $State.ResumedPages says how many. The caller deletes the
    # file after writing the cache. A partial file is plain JSON beside the cache file,
    # <version>.partial.json, and never matches the *.json.gz the cache readers list:
    #   { address, version, versionId, savedOn, pageCount, pages: [ { docId, content } ] }
    param([string]$VersionId, [int]$ThrottleLimit, [string]$PartialPath, [switch]$Resume, [string]$Address, [string]$Version, [hashtable]$State = @{})

    $registry = "https://$($script:TerraformRegistrySource)"
    $listing = Invoke-TerraformRegistryRequest -Uri "$registry/v2/provider-versions/${VersionId}?include=provider-docs"
    $listed = [System.Collections.Generic.List[object]]::new()
    $skipped = [ordered]@{}
    foreach ($item in @($listing.included)) {
        if ($item.type -ne 'provider-docs') { continue }
        $attributes = $item.attributes
        $category = [string]$attributes.category
        if ([string]$attributes.language -ne 'hcl' -or $script:TerraformDocCategories -notcontains $category) {
            $key = "$category ($($attributes.language))"
            $skipped[$key] = 1 + [int]$skipped[$key]
            continue
        }
        $listed.Add([pscustomobject]@{
            DocId       = [string]$item.id
            Category    = $category
            Title       = [string]$attributes.title
            Subcategory = if ([string]::IsNullOrEmpty([string]$attributes.subcategory)) { $null } else { [string]$attributes.subcategory }
            Slug        = [string]$attributes.slug
        })
    }
    foreach ($key in $skipped.Keys) { Write-Verbose "Skipped $($skipped[$key]) docs in category $key" }
    Write-Verbose "Listed $($listed.Count) docs"

    $pages = [System.Collections.Generic.Dictionary[string, string]]::new([System.StringComparer]::Ordinal)
    $State.ResumedPages = 0
    if ($PartialPath -and $Resume -and (Test-Path -LiteralPath $PartialPath -PathType Leaf)) {
        try {
            $partial = [TerraformGraph.Json]::Deserialize([System.IO.File]::ReadAllText($PartialPath), 1024, $true)
            if ([string]$partial['versionId'] -ceq $VersionId) {
                $wanted = [System.Collections.Generic.HashSet[string]]::new([string[]]@($listed.DocId), [System.StringComparer]::Ordinal)
                foreach ($page in @($partial['pages'])) {
                    if ($wanted.Contains([string]$page['docId'])) { $pages[[string]$page['docId']] = [string]$page['content'] }
                }
                $State.ResumedPages = $pages.Count
                Write-Verbose "Resuming from $PartialPath`: $($pages.Count) of $($listed.Count) pages already fetched"
            }
            else {
                Write-Verbose "$PartialPath is for registry version id $($partial['versionId']), not $VersionId; starting over"
            }
        }
        catch {
            Write-Verbose "Ignoring $PartialPath`: $($_.Exception.Message)"
        }
    }

    $savePartial = {
        $document = [ordered]@{
            address   = $Address
            version   = $Version
            versionId = $VersionId
            savedOn   = [datetime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ', [cultureinfo]::InvariantCulture)
            pageCount = $pages.Count
            pages     = [object[]]@(foreach ($docId in $pages.Keys) { [ordered]@{ docId = $docId; content = $pages[$docId] } })
        }
        Write-TerraformGraphTextFile -Path $PartialPath -Text ([TerraformGraph.Json]::Serialize($document, 1024, $true))
    }

    $requests = @(foreach ($doc in $listed) {
            if (-not $pages.ContainsKey($doc.DocId)) { [pscustomobject]@{ Key = $doc.DocId; Uri = "$registry/v2/provider-docs/$($doc.DocId)" } }
        })
    $failed = [System.Collections.Generic.List[object]]::new()
    $sinceCheckpoint = 0
    $fetched = 0
    $finished = $false
    try {
        Invoke-TerraformRegistryRequestSet -Request $requests -ThrottleLimit $ThrottleLimit | ForEach-Object {
            if ($_.Error) {
                $failed.Add($_)
            }
            else {
                $pages[$_.Key] = [string]$_.Value.data.attributes.content
                $fetched++
                $sinceCheckpoint++
                if ($PartialPath -and $sinceCheckpoint -ge $script:TerraformDocCheckpointPages) {
                    & $savePartial
                    $sinceCheckpoint = 0
                }
            }
            Write-Progress -Id 2 -Activity 'Fetching provider docs' -Status "$($pages.Count) of $($listed.Count)" -PercentComplete (100 * $pages.Count / [math]::Max(1, $listed.Count))
        }
        $finished = $failed.Count -eq 0
    }
    finally {
        Write-Progress -Id 2 -Activity 'Fetching provider docs' -Completed
        if ($PartialPath -and $fetched) {
            & $savePartial
            if (-not $finished) { Write-Verbose "Saved $($pages.Count) of $($listed.Count) pages to $PartialPath; rerun with -Resume to continue" }
        }
    }

    if ($failed.Count) {
        $byId = @{}
        foreach ($doc in $listed) { $byId[$doc.DocId] = $doc }
        $names = @($failed | Select-Object -First 10 | ForEach-Object { "$($byId[$_.Key].Category)/$($byId[$_.Key].Slug) ($($_.Error))" })
        $saved = if ($PartialPath) { " The $($pages.Count) pages fetched are saved in $PartialPath for -Resume." } else { '' }
        Stop-TerraformGraphCommand -Throw -Id 'ProviderDocHarvestFailed' -Category ConnectionError -Target $Address -Message "Failed to fetch $($failed.Count) docs: $($names -join '; ')$(if ($failed.Count -gt 10) { '; ...' }). The cache was not written.$saved"
    }

    foreach ($doc in $listed) {
        [pscustomobject]@{
            Category    = $doc.Category
            Title       = $doc.Title
            Subcategory = $doc.Subcategory
            Slug        = $doc.Slug
            Content     = $pages[$doc.DocId]
        }
    }
}
